In [3]:
from numpy.random import randn
import numpy as np

In [2]:
data = {i : randn() for i in range(7)} #Creating a list 7 random number using 'randn' function from NumPy

In [3]:
data #printing the variable contents

{0: 1.1739547182504684,
 1: 0.912118882124111,
 2: 0.6079204149779377,
 3: 0.5004865150355423,
 4: 0.5452652776887412,
 5: 1.8008469818019228,
 6: -0.38724723995077615}

NameError: name 'plt' is not defined

In [6]:
data1 = [[1,2,3],[4,5,6]] #Creating a new data
data1 #Printing values

[[1, 2, 3], [4, 5, 6]]

In [9]:
data1 = np.array(data1) #Converting the same data as a 2 dimensional array

In [10]:
data1 #Printing the values

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
data1.dtype #Figuring out the type of the data store in the variable

dtype('int64')

In [13]:
data1.shape #Finding the dimension of the data stored

(2, 3)

In [14]:
np.arange(15) #Generating a stream of ascending numbers from 1 to 15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.zeros((3,2)) #Creating a 3x2 matrix of zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [16]:
data1 = data1.astype('int32') #Type casting

In [18]:
data1.dtype #Finding the type of data

dtype('int32')

In [20]:
num_string = np.array(['1', '2', '4.5', '7.89'], dtype = np.string_) #Creating an array of strings with number values

In [21]:
num_string.dtype #Printing the type of data stored

dtype('S4')

In [22]:
num_string = num_string.astype(float) #type casting it to numeric

In [23]:
num_string.dtype #Printing the type of data stored

dtype('float64')

In [24]:
num_string #Printing the data to see any visible changes

array([ 1.  ,  2.  ,  4.5 ,  7.89])