In [1]:
from numpy.random import randn
import numpy as np
import pandas as pd

In [2]:
data = {i : randn() for i in range(7)} #Creating a list 7 random number using 'randn' function from NumPy

In [3]:
data #printing the variable contents

{0: 1.1739547182504684,
 1: 0.912118882124111,
 2: 0.6079204149779377,
 3: 0.5004865150355423,
 4: 0.5452652776887412,
 5: 1.8008469818019228,
 6: -0.38724723995077615}

In [61]:
i = 99
n = len(str(i))
print i**2
print i**2/ 10**n
print i**2%10**n

9801
98
1


In [6]:
data1 = [[1,2,3],[4,5,6]] #Creating a new data
data1 #Printing values

[[1, 2, 3], [4, 5, 6]]

In [9]:
data1 = np.array(data1) #Converting the same data as a 2 dimensional array

In [10]:
data1 #Printing the values

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
data1.dtype #Figuring out the type of the data store in the variable

dtype('int64')

In [13]:
data1.shape #Finding the dimension of the data stored

(2, 3)

In [14]:
np.arange(15) #Generating a stream of ascending numbers from 1 to 15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
np.zeros((3,2)) #Creating a 3x2 matrix of zeros

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [16]:
data1 = data1.astype('int32') #Type casting

In [18]:
data1.dtype #Finding the type of data

dtype('int32')

In [20]:
num_string = np.array(['1', '2', '4.5', '7.89'], dtype = np.string_) #Creating an array of strings with number values

In [21]:
num_string.dtype #Printing the type of data stored

dtype('S4')

In [22]:
num_string = num_string.astype(float) #type casting it to numeric

In [23]:
num_string.dtype #Printing the type of data stored

dtype('float64')

In [24]:
num_string #Printing the data to see any visible changes

array([ 1.  ,  2.  ,  4.5 ,  7.89])

In [25]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[2,3,5],[4,5,6]]]) #creating a 3D array

In [26]:
arr3d #Display values

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 5],
        [4, 5, 6]]])

In [27]:
arr3d[0] #Checking 1st element

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
oldval = arr3d.copy() #copying the original values

In [29]:
oldval

array([[[1, 2, 3],
        [4, 5, 6]],

       [[2, 3, 5],
        [4, 5, 6]]])

In [31]:
arr3d[1,0]

array([2, 3, 5])

In [32]:
arr3d[1:6]

array([[[2, 3, 5],
        [4, 5, 6]]])

In [1]:
range(50)

range(0, 50)

In [2]:
print(range(50))

range(0, 50)


In [3]:
range(1,50)


range(1, 50)

In [10]:
s = 'jkfkjnsdlfkLNDFJLKNG'

s = list(s)
for i in range(len(s)):
    if s[i].islower():
        s[i] = s[i].upper()
    else:
        s[i] = s[i].lower()
''.join(s)

'JKFKJNSDLFKlndfjlkng'

In [31]:
a,n = map(str, raw_input().split(' '))

1 2


In [32]:
def hypo(a,b):
    a_sq = a**2
    b_sq = b**2
    c_sq = a_sq + b_sq
    c = c_sq**0.5
    return c

hypo(3,4)

5.0

In [34]:
n = 5

if n%5 == 0:
    for i in range(n):
        print(5),
    

5 5 5 5 5


In [26]:
print 55555

55555


In [37]:
a = [12,12,1,1]
a.remove(12)
a


[12, 1, 1]

In [38]:
5/3

1

In [44]:
s= 'asfasf'
s  = list(s)
[ord(x) for x in s]

[97, 115, 102, 97, 115, 102]

In [54]:
ord('-')

45

In [50]:
chr(90)

'Z'

In [62]:
int(3.9)

3

In [64]:
int(3.9+1)

4

In [90]:
i = [1,2,3]
j = [2,3,4]
a = []
a.append(i)
a.append(j)
a

[[1, 2, 3], [2, 3, 4]]

In [92]:

a[0][0] =100
a

[[100, 2, 3], [2, 3, 4]]

In [87]:
a

[0, 0]

In [100]:
def fib(n):
    if n < 2:
        return n
    return fib(n-2) + fib(n-1)

a = map(fib, range(0, 10))
s = 0
for i in range(len(a)):
    if a[i]%2 == 0:
        s = s + i
        
print s

18


In [2]:
t = int(raw_input())
a = set(list(str(raw_input())))
print a
for i in xrange(t-1):
    b = set(list(str(raw_input())))
    a = a ^ b
    print a
    
print len(list(a))

3
abcdde
set(['a', 'c', 'b', 'e', 'd'])
baccd
set(['e'])
baccd
set(['a', 'c', 'b', 'e', 'd'])
5


In [3]:
a = set(list('abcdde'))
b = set(list('baccd'))

print a, b


set(['a', 'c', 'b', 'e', 'd']) set(['a', 'c', 'b', 'd'])


In [7]:
a = a.intersection(b)
a

{'a', 'b', 'c', 'd'}

In [5]:
a = [1,2,3,4,5]
i = 4
sum(a[i:])

5

In [20]:
#!/usr/bin/py
def lonelyinteger(a):
    d = dict()
    for i in a:
        if i in d:
            d[i] = d[i] + 1
        else:
            d[i] = 1
    print d
    for i in d:
        if d[i] == 1:
            return i
    
    
    
    return answer
if __name__ == '__main__':
    a = input()
    b = map(int, raw_input().strip().split(" "))
    print lonelyinteger(b)    
    

3
1 1 2
{1: 2, 2: 1}
2


In [23]:
import collections
import re

In [30]:
a = collections.defaultdict(lambda: 1)
a['f'] +=1
print a

defaultdict(<function <lambda> at 0x103f112a8>, {'f': 2})


In [36]:

def words(text): return re.findall('[a-z]+', text.lower()) 
a = words(file('big.txt').read())

In [60]:
'the' in a

True

In [50]:
import re, collections

def words(text): return re.findall('[a-z]+', text.lower()) 

def train(features):
    model = collections.defaultdict(lambda: 1)
    for f in features:
        model[f] += 1
    return model

NWORDS = train(words(file('big.txt').read()))

alphabet = 'abcdefghijklmnopqrstuvwxyz'

def edits1(word):
    splits     = [(word[:i], word[i:]) for i in range(len(word) + 1)]
    deletes    = [a + b[1:] for a, b in splits if b]
    transposes = [a + b[1] + b[0] + b[2:] for a, b in splits if len(b)>1]
    replaces   = [a + c + b[1:] for a, b in splits for c in alphabet if b]
    inserts    = [a + c + b     for a, b in splits for c in alphabet]
    return set(deletes + transposes + replaces + inserts)

def known_edits2(word):
    return set(e2 for e1 in edits1(word) for e2 in edits1(e1) if e2 in NWORDS)

def known(words): return set(w for w in words if w in NWORDS)

def correct(word):
    candidates = known([word]) or known(edits1(word)) or known_edits2(word) or [word]
    return max(candidates, key=NWORDS.get)

In [57]:
correct('aeronautical')

'aeronautical'

In [15]:
def merge(A,B):
    indexA = len(A)-1;
    indexB = len(B)-1;
    while indexA >=0 and indexB>=0:
        if A[indexA] > B[indexB]:
            A[indexA+indexB+1] = A[indexA]
            indexA -= 1
        else:
            A[indexA+indexB+1] = B[indexB]
            indexB -= 1
    while indexB >= 0:
        A[indexB] = B[indexB]
        indexB -= 1
merge(a,b)

IndexError: list assignment index out of range

In [24]:
a = [1,2,11,12,56]
b = [0,3,11,41,44,45]

def merge(a, b):
    """
    a and b are two sorted lists
    """
    i = 0
    j = 0
    c =  []
    while i < len(a) and j < len(b):
        if a[i] < b[j]:
            c.append(a[i])
            i += 1
        else:
            c.append(b[j])
            j += 1
    if i < len(a):
        while i < len(a):
            c.append(a[i])
            i += 1
    if j < len(b):
        while j < len(b):
            c.append(b[j])
            j += 1
    return c
merge(a,b)

[0, 1, 2, 3, 11, 11, 12, 41, 44, 45]